name: dorothea

services:
  pmacct-probe:
    build:
      context: ../..
      dockerfile: Dockerfile.dorothea
    network_mode: "host"
    volumes:
      - .:/dorothea

  # YOUR ACTIONS: Remove the example service below and add your own
  guinea-pig:
    build:
      context: ..
      dockerfile: Dockerfile.guineapig
    networks:
      - dorothea-net
    hostname: guinea-pig
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "service ssh status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'     # Limit to 1.0 CPUs
          memory: 1024M    # Limit to 1024 MB of RAM
        reservations:
          cpus: '0.25'    # Reserve 0.5 CPUs
          memory: 512M    # Reserve 512 MB of RAM

  attacker:
    build:
        context: .
        dockerfile: Dockerfile.attacker
    networks:
      - dorothea-net
    depends_on:
      guinea-pig:
        condition: service_healthy
    command: ["hydra", "-l", "dorothea", "-P", "rockyou.txt", "ssh://guinea-pig"]
      
networks:
  dorothea-net:
    driver: bridge
    name: dorothea-net 