# Attacker 
FROM kalilinux/kali-last-release:latest

# Install nmap package
RUN apt-get update && \
    apt-get install -y \
    hydra

RUN wget -O rockyou.txt https://raw.githubusercontent.com/josuamarcelc/common-password-list/main/rockyou.txt/rockyou_1.txt
