name: dorothea

services:
  pmacct-probe:
    build:
      context: .
      dockerfile: Dockerfile.dorothea
    network_mode: "host"
    volumes:
      # This directory is mounted to retrieve the pmacct configuration
      # and to dump the captured netflows outside the container.
      - .:/dorothea

  # YOUR ACTIONS: Remove the example service below and add your own
