name: dorothea

services:
  pmacct-probe:
    build:
      context: .
      dockerfile: Dockerfile.dorothea
    network_mode: "host"
    volumes:
      - .:/dorothea

  # YOUR ACTIONS: Remove the example service below and add your own
  guinea-pig:
    image: ubuntu:noble
    command: 
      - /bin/bash
      - -c
      - |
        apt-get update
        apt-get install -y nmap
        nping scanme.nmap.org
    network_mode: "bridge"