name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Docker image with Dockerfile.dorothea
      run: docker build . --file Dockerfile.dorothea --tag dorothea:$(date +%s)
    
    - name: Build Docker image with Dockerfile.guineapig
      run: docker build . --file Dockerfile.guineapig --tag guineapig:$(date +%s)

    - name: Build Docker image with Dockerfile.third
      run: docker build . --file Dockerfile.attacker --tag attacker:$(date +%s)
