name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  dorothea-container-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Docker image with Dockerfile.dorothea
      run: docker build . --file Dockerfile.dorothea --tag dorothea:$(date +%s)
    

  example-container-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Docker image with Dockerfile.guineapig
      run: docker build ./examples --file ./examples/Dockerfile.guineapig --tag guineapig:$(date +%s)

    - name: Build Docker image with Dockerfile.attacker
      run: docker build ./examples/port-scan --file ./examples/port-scan/Dockerfile.attacker --tag attacker:$(date +%s)

    - name: Build Docker image with Dockerfile.attacker
      run: docker build ./examples/ssh-brute-force --file ./examples/ssh-brute-force/Dockerfile.attacker --tag attacker:$(date +%s)