name: dorotheaCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  dorothea-container-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Docker image with Dockerfile.dorothea
      run: docker build . --file Dockerfile.dorothea --tag dorothea:$(date +%s)
    